# 使用 Python 3.9 的 Alpine 映像作為基礎映像
FROM python:3.9-alpine

# 設定工作目錄
WORKDIR /app

# 複製當前目錄的檔案到容器內的 /app 目錄
COPY . /app

# 安裝系統相依套件和 Python 套件
RUN apk add --no-cache gcc musl-dev libffi-dev && \
    pip install --no-cache-dir -r requirements.txt && \
    apk del gcc musl-dev libffi-dev

# 暴露 5000 端口
EXPOSE 5000

# 設定容器啟動時執行的命令
CMD ["python", "app.py"]
