# 使用 Node.js 官方映像
FROM node:18

# 建立應用目錄
WORKDIR /app

# 複製檔案
# COPY package.json ./
# 改用 git clone
RUN git clone https://github.com/RayLin9981/docker101.git 
# 切換至 git 目錄
WORKDIR /app/docker101/nodejs/catdog-api

RUN npm install

# COPY index.js ./

# 啟動應用
CMD ["npm", "start"]

# 開放 port
EXPOSE 3000

